Michael Gutowski
Jack Fiengo

This is an example of how we can use a scikit learn package. I just picked the first dataset and model I could find, so we should definitely do some more research on that and experiment around a bit. Also I haven't gotten the last line of code to work yet still trying to figure it out.

In [10]:
import pandas as pd
df_9192 = pd.read_csv('michaelJordanStats9192.csv')

In [11]:
df_9192.head()

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc
0,1,1,1991-11-01,28-257,CHI,NaN,PHI,W (+20),1,30:00,...,1,4,5,4,3,1,2,2,26,22.6
1,2,2,1991-11-02,28-258,CHI,@,MIL,L (-2),1,42:00,...,0,3,3,3,5,1,4,1,46,37.6
2,3,3,1991-11-05,28-261,CHI,NaN,GSW,L (-8),1,46:00,...,2,5,7,4,1,1,5,5,40,30.6
3,4,4,1991-11-06,28-262,CHI,@,BOS,W (+19),1,38:00,...,0,3,3,6,1,1,2,2,44,36.2
4,5,5,1991-11-08,28-264,CHI,NaN,DAL,W (+16),1,36:00,...,1,6,7,5,4,0,0,1,26,28.3

In [12]:
df_9192.rename(columns={'Unnamed: 5': 'Home/Away'}, inplace=True)
df_9192.rename(columns={'Unnamed: 7': 'Spread'}, inplace=True)
df_9192["Home/Away"].replace({"@": "Away"}, inplace=True)
df_9192["Home/Away"].fillna("Home", inplace=True)
df_9192.head()

,Rk,G,Date,Age,Tm,Home/Away,Opp,Spread,GS,MP,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc
0,1,1,1991-11-01,28-257,CHI,Home,PHI,W (+20),1,30:00,...,1,4,5,4,3,1,2,2,26,22.6
1,2,2,1991-11-02,28-258,CHI,Away,MIL,L (-2),1,42:00,...,0,3,3,3,5,1,4,1,46,37.6
2,3,3,1991-11-05,28-261,CHI,Home,GSW,L (-8),1,46:00,...,2,5,7,4,1,1,5,5,40,30.6
3,4,4,1991-11-06,28-262,CHI,Away,BOS,W (+19),1,38:00,...,0,3,3,6,1,1,2,2,44,36.2
4,5,5,1991-11-08,28-264,CHI,Home,DAL,W (+16),1,36:00,...,1,6,7,5,4,0,0,1,26,28.3

In [14]:
df_9192['W/L'] = df_9192['Spread'].str.extract('([W|L])', expand=True)
df_9192.head()

,Rk,G,Date,Age,Tm,Home/Away,Opp,Spread,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,W/L
0,1,1,1991-11-01,28-257,CHI,Home,PHI,W (+20),1,30:00,...,4,5,4,3,1,2,2,26,22.6,W
1,2,2,1991-11-02,28-258,CHI,Away,MIL,L (-2),1,42:00,...,3,3,3,5,1,4,1,46,37.6,L
2,3,3,1991-11-05,28-261,CHI,Home,GSW,L (-8),1,46:00,...,5,7,4,1,1,5,5,40,30.6,L
3,4,4,1991-11-06,28-262,CHI,Away,BOS,W (+19),1,38:00,...,3,3,6,1,1,2,2,44,36.2,W
4,5,5,1991-11-08,28-264,CHI,Home,DAL,W (+16),1,36:00,...,6,7,5,4,0,0,1,26,28.3,W

In [15]:
training_columns = ['Home/Away', 'PTS', 'AST', 'STL', 'BLK', 'TOV', 'FG%']
x = df_9192[training_columns]
y = df_9192['W/L']

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x['Home/Away'] = le.fit_transform(x['Home/Away'])
y = le.fit_transform(y)

C:\Users\fieng\AppData\Local\Temp\ipykernel_15152\162893458.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Home/Away'] = le.fit_transform(x['Home/Away'])

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [26]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=1)
rfc.fit(x_train, y_train)

RandomForestClassifier(random_state=1)

In [27]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, rfc.predict(x_test))

0.25